# 1️⃣ Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-app'
        static_configs:
          - targets: ['spring-service.devops.svc.cluster.local:8089']
        metrics_path: /student/actuator/prometheus

---

# 2️⃣ PersistentVolumeClaim for Grafana
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# 3️⃣ Monitoring Deployment (Prometheus + Grafana)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus

        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

---

# 4️⃣ Service for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: devops
spec:
  selector:
    app: monitoring
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30900
  type: NodePort

---

# 5️⃣ Service for Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: devops
spec:
  selector:
    app: monitoring
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30700
  type: NodePort
